name: Conbee API Client Pester Tests

on:
  push:
    branches: [ main ]
    paths:
      - 'src/ps/conbee-api-client/**'
      - 'src/ps/tests/**'
      - '.github/workflows/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/ps/conbee-api-client/**'
      - 'src/ps/tests/**'
      - '.github/workflows/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Powershell deps
        shell: pwsh
        run: |
          Install-Module Microsoft.PowerShell.SecretManagement -Force -Scope CurrentUser
          Install-Module Microsoft.PowerShell.SecretStore -Force -Scope CurrentUser

      - name: Run Pester tests
        shell: pwsh
        run: |
          Invoke-Pester -Path ./src/ps/tests -Output Detailed
