name: Publish to PSGallery

on:
  push:
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Powershell deps
        shell: pwsh
        run: |
          Install-Module Microsoft.PowerShell.SecretManagement -Force -Scope CurrentUser
          Install-Module Microsoft.PowerShell.SecretStore -Force -Scope CurrentUser

      - name: Publish to PSGallery
        shell: pwsh
        env:
          NUGET_API_KEY: ${{ secrets.NUGGETS }}
        run: |
          Publish-Module -Path ./src/ps/conbee-api-client -NuGetApiKey $env:NUGET_API_KEY
